<?php
/*
Plugin Name: Cache-Control
Plugin URI:  https://www.geeky.software/wordpress-plugins/cache-control/
Description: Configurable HTTP Cache-Control headers for webpages generated by WordPress.
Version:     1.0
Author:      Geeky Software
Author URI:  https://www.geeky.software/
License:     GPLv3
License URI: https://www.gnu.org/licenses/gpl-3.0.html
*/

if ( !defined('ABSPATH') ) {
    header( 'HTTP/1.1 403 Forbidden' );
    exit(   'HTTP/1.1 403 Forbidden' );
}

$cache_control_options = array(
    'front_page'   => array(
        'id'       => 'front_page',
        'name'     => 'Front page',
        'max_age'  => 300,           //          5 min
        's_maxage' => 150            //          2 min 30 sec
    ),
    'singles'      => array(
        'id'       => 'singles',
        'name'     => 'Posts',
        'max_age'  => 600,           //         10 min
        's_maxage' => 60             //          1 min
    ),
    'pages'        => array(
        'id'       => 'pages',
        'name'     => 'Pages',
        'max_age'  => 1200,          //         20 min
        's_maxage' => 300            //          5 min
    ),
    'home'         => array(
        'id'       => 'home',
        'name'     => 'Main index',
        'max_age'  => 180,           //          3 min
        's_maxage' => 45,            //                45 sec
        'paged'    => 5              //                 5 sec
    ),
    'categories'   => array(
        'id'       => 'categories',
        'name'     => 'Categories',
        'max_age'  => 900,           //         15 min
        's_maxage' => 300,           //          5 min
        'paged'    => 8              //                 8 sec
    ),
    'tags'         => array(
        'id'       => 'tags',
        'name'     => 'Tags',
        'max_age'  => 900,           //         15 min
        's_maxage' => 300,           //          5 min
        'paged'    => 10             //                 8 sec
    ),
    'authors'      => array(
        'id'       => 'authors',
        'name'     => 'Authors',
        'max_age'  => 1800,          //         30 min
        's_maxage' => 600,           //         10 min
        'paged'    => 10             //                10 sec
    ),
    'dates'        => array(
        'id'       => 'dates',
        'name'     => 'Dated archives',
        'max_age'  => 10800,         // 3 hours
        's_maxage' =>  2700          //         45 min
    ),
    'feeds'        => array(
        'id'       => 'feeds',
        'name'     => 'Feeds',
        'max_age'  => 5400,          // 1 hours 30 min
        's_maxage' => 600            //         10 min
    ),
    'attachment'   => array(
        'id'       => 'attachment',
        'name'     => 'Attachments',
        'max_age'  => 10800,         // 3 hours
        's_maxage' =>  2700          //         45 min
    ),
    'search'        => array(
        'id'       => 'search',
        'name'     => 'Search results',
        'max_age'  => 1800,          //         30 min
        's_maxage' => 600            //         10 min
    ),
    'notfound'     => array(
        'id'       => 'notfound',
        'name'     => '404 Not Found',
        'max_age'  => 900,           //         15 min
        's_maxage' => 300            //          5 min
)   );

function stale_factorer( $factor ) {
    if ( is_paged() && is_int( $factor ) && $factor > 0 ) {
        return $factor * (get_query_var('paged') - 1);
    }
    return 0;
}

function build_directive_header( $max_age, $s_maxage ) {
    $directive = "";
    if ( !empty( $max_age ) && is_int( $max_age ) && $max_age > 0) {
        $directive = "max-age=$max_age";
    }
    if ( !empty( $s_maxage ) && is_int( $s_maxage ) && $s_maxage > 0 && $s_maxage != $max_age ) {
        if ( !$directive != "" ) {
            $directive = "public";
        }
        $directive = "$directive, s-maxage=$s_maxage";
    }
    if ( $directive != "" ) {
        return $directive;
    } else {
        return "no-cache, no-store, must-revalidate";
}   }

function build_directive_from_option( $id ) {
    global $cache_control_options;

    $option = $cache_control_options[$id];

    $page_factor = 0;
    if ( isset( $option['paged'] ) ) {
        $page_factor = get_option( 'cache_control_' . $option['id'] . '_paged', $option['paged'] );
    }

    $max_age  = get_option( 'cache_control_' . $option['id'] . '_max_age',  $option['max_age']  ) + stale_factorer($page_factor);
    $s_maxage = get_option( 'cache_control_' . $option['id'] . '_s_maxage', $option['s_maxage'] ) + stale_factorer($page_factor);

    return build_directive_header( $max_age, $s_maxage );
}

function select_directive() {
    if ( is_preview() || is_user_logged_in() || is_trackback() || is_admin() ) {
        return build_directive_header( false, false );
    } elseif ( is_feed() ) {
        return build_directive_from_option( 'feeds' );
    } elseif ( is_front_page() && !is_paged() ) {
        return build_directive_from_option( 'front_page' );
    } elseif ( is_single() ) {
        return build_directive_from_option( 'singles' );
    } elseif ( is_page() ) {
        return build_directive_from_option( 'pages' );
    } elseif ( is_home() ) {
        return build_directive_from_option( 'home' );
    } elseif ( is_category() ) {
        return build_directive_from_option( 'categories' );
    } elseif ( is_tag() ) {
        return build_directive_from_option( 'tags' );
    } elseif ( is_author() ) {
        return build_directive_from_option( 'auhtors' );
    } elseif ( is_attachment() ) {
        return build_directive_from_option( 'attachment' );
    } elseif ( is_search() ) {
        return build_directive_from_option( 'search' );
    } elseif ( is_404() ) {
        return build_directive_from_option( 'notfound' );
    } elseif ( is_date() ) {
        if (   ( is_year()  && strcmp(get_the_time('Y'), date('Y'))     < 0 )
            || ( is_month() && strcmp(get_the_time('Y-m'), date('Y-m')) < 0 )
            || ( ( is_day() || is_time() ) && strcmp(get_the_time('Y-m-d'), date('Y-m-d')) < 0 ) ) {
            return build_directive_from_option( 'dates' );
        } else {
            return build_directive_from_option( 'home' );
    }   }

    return build_directive_header( false, false );
}

function send_http_header( $directives ) {
    if ( !empty( $directives ) ) {
        header ( "Cache-Control: $directives" );
}   }

function cache_control_send_headers() {
    send_http_header( select_directive() );
}

add_action( 'template_redirect', 'cache_control_send_headers' );

if ( is_admin() ) {
    require_once( dirname(__file__) . '/admin.php' );
}

?>
